### ISSUE TITLE
What should be passed to <unique_user_identity>

### ISSUE THREAD

**Issue by Pruthvirajcodewave** [NetcoreSolutions/Smartech-React-Native#2]
Hi 
I am not sure what to pass in these events params.
Should it be something like onesignal_id/ FCM ID ?
smartech.setIdentity(<unique_user_identity>)
smartech.login(<unique_user_identity>)

Also how to Register for Netcore with the APP ID in react native ? In Android its NetcoreSDK.register(this, "APP ID THAT YOU GET FROM SMARTECH PANEL");

**Comment by icodebuster** [comment]
@Pruthvirajcodewave 
In iOS you can refer [this](https://github.com/NetcoreSolutions/Smartech-React-Native/blob/master/docs/integration.md) doc.

```objective-c
[[NetCoreSharedManager  sharedInstance] setUpAppGroup:@"group.your.appgroup"];
[[NetCoreSharedManager  sharedInstance] handleApplicationLaunchEvent:launchOptions forApplicationId:@"YOUR_APP_ID_FROM_SMARTECH_PANEL"];
//set up push delegate
[NetCorePushTaskManager  sharedInstance].delegate = (id)self;
```

**Comment by Pruthvirajcodewave** [comment]
Hi, How to register for netcore in react native? 

Below code is for native android.
NetcoreSDK.register(this, "APP ID THAT YOU GET FROM SMARTECH PANEL");

**My question is to react native both **android and ios.****
