### ISSUE TITLE
How to register for netcore sdk in react native?

### ISSUE THREAD

**Issue by Pruthvirajcodewave** [NetcoreSolutions/Smartech-React-Native#3]
Hi, npm has methods like smartech. setIdentity, smartech.clearIdentity ,smartech.login etc. But I could not find any method for registering to the library with the APP ID we get from the panel.

I tried to write a method like below in the npm code itself,

` @ReactMethod
  public void register(String appId, Promise promise) {
    try {
      NetcoreSDK.register(reactContext, appId);
      promise.resolve(true);
    } catch (Exception e) {
      promise.reject(e);
    }
  }` 

but getting an error as it expects the applicaiton context as a parameter. Please help me solve this.

**Comment by Pruthvirajcodewave** [comment]
Got this sorted out. 
We need to put the `NetcoreSDK.register(this, "APP ID THAT YOU GET FROM SMARTECH PANEL");
` in MainApplication onCreate method. import statement for this is `import in.netcore.smartechfcm.NetcoreSDK;`  And put the below code `implementation 'in.netcore.smartechfcm:smartech-fcm:1.2.9'
implementation 'com.google.code.gson:gson:2.8.5'
implementation 'com.google.firebase:firebase-messaging:17.6.0'` app level build.gradle.

**Comment by monikakale24** [comment]
Please update Smartech dependancy with the latest version. For detailed integration document visit the given [link](https://docs.netcoresmartech.com/docs/android-sdk).
