### ISSUE TITLE
Please fix the doc guide

### ISSUE THREAD

**Issue by truongthanh1303** [NetcoreSolutions/Smartech-React-Native#4]
Hi,

I follow this guide to add the handling URL Link for iOS [https://github.com/NetcoreSolutions/Smartech-React-Native/blob/master/docs/integration.md#to-handle-url-link]
It has wrong typo
<img width="909" alt="Screen Shot 2019-09-08 at 17 01 13" src="https://user-images.githubusercontent.com/7240446/64486703-8e6e6580-d25a-11e9-8767-e1b7b9feca8c.png">

**Comment by icodebuster** [comment]
Moved the documentation [here](https://docs.netcoresmartech.com/docs/react-native-sdk-integration)
