### ISSUE TITLE
Failed to run (IOS)

### ISSUE THREAD

**Issue by alfathdirk** [NetcoreSolutions/Smartech-React-Native#6]
![error](https://i.imgur.com/04s0zkT.png)

i get this error while build on react native for ios

**Comment by TrushalRank** [comment]
@alfathdirk , I have facing same issue. Do you have find any solution?

**Comment by icodebuster** [comment]
@alfathdirk & @TrushalRank 
Please update your smartech-react-native plugin as well as the Netcore-Smartech-iOS-SDK pod

**Comment by TrushalRank** [comment]
@icodebuster , I have using latest plugin.
"smartech-react-native": "^1.1.8"

and in iOS podfile use as,
pod 'smartech-react-native', :path => '../node_modules/smartech-react-native'

**Comment by icodebuster** [comment]
@TrushalRank 

In your Podfile please add
source 'https://cdn.cocoapods.org/'
source 'https://github.com/NetcoreSolutions/Specs.git'

At the app level's Podfile add the below line
pod 'Netcore-Smartech-iOS-SDK'

Then run the `pod install` command.
The Netcore SDK version should be greater that 2.5.3

**Comment by TrushalRank** [comment]
@icodebuster  I also tried with that, but not works.

**Comment by icodebuster** [comment]
What is the version of the SDK that you are using.

**Comment by TrushalRank** [comment]
@icodebuster , you means that in podfile?

**Comment by icodebuster** [comment]
Yes, in your app's Podfile.

**Comment by TrushalRank** [comment]
In pod file not mentioned any version. i am using,
pod 'smartech-react-native', :path => '../node_modules/smartech-react-native'

**Comment by icodebuster** [comment]
Can you delete the node_module and run npm install, if the issue still persists, please contact Netcore's Support Team.

**Comment by TrushalRank** [comment]
Okay will check that. Thanks.

**Comment by TrushalRank** [comment]
@icodebuster , Thanks. it's working fine when i remove smartech folder from node-module and re-install it.
